//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.7905
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JappUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JappUI.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort?.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string Aborted {
            get {
                return ResourceManager.GetString("Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A programming operation  is in progress. Would you like to abort it?.
        /// </summary>
        internal static string AbortOpInProgress {
            get {
                return ResourceManager.GetString("AbortOpInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Error!.
        /// </summary>
        internal static string AddressError {
            get {
                return ResourceManager.GetString("AddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error.
        /// </summary>
        internal static string ConfigurationError {
            get {
                return ResourceManager.GetString("ConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s an error with the configuration file..
        /// </summary>
        internal static string ConfigurationErrorMessage {
            get {
                return ResourceManager.GetString("ConfigurationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected..
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID: {0} Revision: {1}.
        /// </summary>
        internal static string DeviceIdAndRevision {
            get {
                return ResourceManager.GetString("DeviceIdAndRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device detected does not match user selection!.
        /// </summary>
        internal static string DeviceIdDoesNotMatch {
            get {
                return ResourceManager.GetString("DeviceIdDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not supported. If your device family is on the list you may be able to get JAPP to work with your device by adding to the devices list on japp.config file and restarting JAPP..
        /// </summary>
        internal static string DeviceNotSupported {
            get {
                return ResourceManager.GetString("DeviceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device recognized as: {0}.
        /// </summary>
        internal static string DeviceRecognizedAs {
            get {
                return ResourceManager.GetString("DeviceRecognizedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected..
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erasing part....
        /// </summary>
        internal static string ErasingPart {
            get {
                return ResourceManager.GetString("ErasingPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed!.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX file loaded successfully..
        /// </summary>
        internal static string HEXFileLoaded {
            get {
                return ResourceManager.GetString("HEXFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX file unloaded..
        /// </summary>
        internal static string HEXFileUnloaded {
            get {
                return ResourceManager.GetString("HEXFileUnloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device does not have enough memory for this file..
        /// </summary>
        internal static string InsufficientDeviceMemory {
            get {
                return ResourceManager.GetString("InsufficientDeviceMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming configuration bits....
        /// </summary>
        internal static string ProgrammingConfigBits {
            get {
                return ResourceManager.GetString("ProgrammingConfigBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming memory....
        /// </summary>
        internal static string ProgrammingDevice {
            get {
                return ResourceManager.GetString("ProgrammingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading program memory (0x{0} - 0x{1})....
        /// </summary>
        internal static string ReadingProgramMemory {
            get {
                return ResourceManager.GetString("ReadingProgramMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for next operation..
        /// </summary>
        internal static string ReadyForNextOperation {
            get {
                return ResourceManager.GetString("ReadyForNextOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target running....
        /// </summary>
        internal static string TargetRunning {
            get {
                return ResourceManager.GetString("TargetRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying program memory....
        /// </summary>
        internal static string VerifyingProgramMemory {
            get {
                return ResourceManager.GetString("VerifyingProgramMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
